# Linear Algebra practice

Based on Intro to Linear Algebra for ML from ML Mastery

In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3])
print(v)

[1 2 3]


In [4]:
b = np.array([4,5,6])
print(v*b)

[ 4 10 18]


In [5]:
print(v+b)

[5 7 9]


In [6]:
print(v-b)

[-3 -3 -3]


In [7]:
print(v/b)

[0.25 0.4  0.5 ]


In [11]:
print(b % v)

[0 1 0]


In [8]:
print(np.dot(v,b))

32


In [10]:
print(np.cross(v,b))

[-3  6 -3]


# Matrices

In [3]:
matrix_a = np.array([[1,2,3], [4,5,6]])

In [4]:
print(matrix_a)

[[1 2 3]
 [4 5 6]]


In [5]:
matrix_b = np.array([[5,6,7], [7,8,9]])

In [6]:
print(matrix_b)

[[5 6 7]
 [7 8 9]]


In [7]:
print(matrix_a + matrix_b)

[[ 6  8 10]
 [11 13 15]]


In [9]:
print(matrix_a.dot(matrix_b))

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [11]:
matrix_c = np.array([[1,2], [3,4], [5,6]])

In [12]:
print(matrix_a.dot(matrix_c))

[[22 28]
 [49 64]]


In [13]:
print(np.dot(matrix_a, matrix_c))

[[22 28]
 [49 64]]


In [15]:
print(np.cross(matrix_a, matrix_b))

[[-4  8 -4]
 [-3  6 -3]]


In [17]:
P = np.array([[8,2], [3,9], [5,6]])
print(P)
Q = P.T
print(Q)

[[8 2]
 [3 9]
 [5 6]]
[[8 3 5]
 [2 9 6]]


In [18]:
R = np.array([[1.0,2.0], [3.0,4.0]])
S = np.linalg.inv(R)
print(S)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [19]:
# determinant
print(np.linalg.det(R))

-2.0000000000000004


In [20]:
# trace
print(np.trace(P))

17


In [21]:
# rank
print(np.linalg.matrix_rank(R))

2
