# Linear Algebra practice

Based on Intro to Linear Algebra for ML from ML Mastery

In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3])
print(v)

[1 2 3]


In [4]:
b = np.array([4,5,6])
print(v*b)

[ 4 10 18]


In [5]:
print(v+b)

[5 7 9]


In [6]:
print(v-b)

[-3 -3 -3]


In [7]:
print(v/b)

[0.25 0.4  0.5 ]


In [11]:
print(b % v)

[0 1 0]


In [8]:
print(np.dot(v,b))

32


In [10]:
print(np.cross(v,b))

[-3  6 -3]
